import { useState } from 'react';
import type { AssessmentView } from '../assessmentView';
import { taskTwoEcgCases, taskTwoEcgOptions, taskTwoPatternCases, taskTwoPatternOptions } from './catalog';
import { markTaskTwo } from './marking';
import type { PatternResponse, TaskTwoResponses, TaskTwoScore } from './marking';
import { loadTaskTwoAttempts, saveTaskTwoAttempt } from './store';

const emptyPattern=():PatternResponse=>({diagnosis:'',explanation:''});
const emptyResponses=():TaskTwoResponses=>({snrtLocation:'',snrtPurpose:'',patterns:{ARP:emptyPattern(),ERP:emptyPattern(),AVNRT:emptyPattern()},wenckebach:emptyPattern(),ecgAnswers:['','','','','']});
const uid=()=>typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;

function PatternStrip({kind}:{kind:string}){return <svg className="task-two-strip" viewBox="0 0 640 120" role="img" aria-label={`Synthetic educational ${kind} tracing`}><path d="M0 70 L55 70 66 28 74 98 84 70 145 70 155 44 164 70 220 70 232 20 244 100 258 70 320 70 330 48 340 70 405 70 417 25 430 96 444 70 505 70 516 50 526 70 590 70 602 30 614 94 628 70 640 70" fill="none" stroke="currentColor" strokeWidth="3"/><text x="12" y="22">{kind}</text></svg>}

export function TaskTwoAssessment({assessmentView}:{readonly assessmentView:AssessmentView}){
 const instructor=assessmentView==='instructor'; const [responses,setResponses]=useState<TaskTwoResponses>(emptyResponses); const [result,setResult]=useState<TaskTwoScore|null>(null); const [attempts,setAttempts]=useState(()=>loadTaskTwoAttempts());
 const updatePattern=(id:'ARP'|'ERP'|'AVNRT',patch:Partial<PatternResponse>)=>setResponses(r=>({...r,patterns:{...r.patterns,[id]:{...r.patterns[id],...patch}}}));
 const submit=()=>{const next=markTaskTwo(responses);setResult(next);setAttempts(saveTaskTwoAttempt({id:uid(),createdAtIso:new Date().toISOString(),result:next}));};
 return <main className="assessment-shell"><header className="assessment-header"><div><span className="assessment-eyebrow">TASK 2 · 22 MARKS</span><h1>Sinus-node recovery, refractoriness and AV block</h1><p>Identify synthetic educational EGM/ECG patterns and explain the defining findings.</p></div><a className="assessment-back-link" href="/?mode=assessment">Interval trainer</a></header>
 <nav className="assessment-task-nav"><a href="/?mode=assessment&task=1">Task 1</a><a className="active" href="/?mode=assessment&task=2">Task 2</a></nav>
 {result&&<section className="task-two-scorebar"><strong>{result.score}/22</strong><span>SNRT {result.snrt.score}/3</span><span>ARP/ERP/AVNRT {result.patternRecognition.score}/9</span><span>Wenckebach {result.wenckebach.score}/5</span><span>ECGs {result.ecg.score}/5</span></section>}
 <section className="task-two-grid"><article className="assessment-panel task-two-card"><h2>1. SNRT — 3 marks</h2><PatternStrip kind="SNRT"/><label>Where is SNRT measured?<textarea value={responses.snrtLocation} onChange={e=>setResponses(r=>({...r,snrtLocation:e.target.value}))}/></label><label>Why is SNRT measured?<textarea value={responses.snrtPurpose} onChange={e=>setResponses(r=>({...r,snrtPurpose:e.target.value}))}/></label>{instructor&&<div className="instructor-answer-key"><strong>Answer key</strong><span>HRA atrial electrogram; last paced A to first returning sinus A. Assesses sinus-node recovery/dysfunction after overdrive pacing.</span></div>}</article>
 {taskTwoPatternCases.map(c=><article className="assessment-panel task-two-card" key={c.id}><h2>{c.label} — 3 marks</h2><PatternStrip kind={c.id}/><label>Diagnosis<select value={responses.patterns[c.id].diagnosis} onChange={e=>updatePattern(c.id,{diagnosis:e.target.value})}><option value="">Select…</option>{taskTwoPatternOptions.slice(0,3).map(o=><option key={o}>{o}</option>)}</select></label><label>Explain the defining finding<textarea value={responses.patterns[c.id].explanation} onChange={e=>updatePattern(c.id,{explanation:e.target.value})}/></label>{instructor&&<div className="instructor-answer-key"><strong>{c.correctDiagnosis}</strong><span>{c.explanationConcepts.join('; ')}</span></div>}</article>)}
 <article className="assessment-panel task-two-card"><h2>Wenckebach — 5 marks</h2><PatternStrip kind="Wenckebach"/><label>Diagnosis<select value={responses.wenckebach.diagnosis} onChange={e=>setResponses(r=>({...r,wenckebach:{...r.wenckebach,diagnosis:e.target.value}}))}><option value="">Select…</option>{taskTwoPatternOptions.map(o=><option key={o}>{o}</option>)}</select></label><label>Explain the sequence<textarea value={responses.wenckebach.explanation} onChange={e=>setResponses(r=>({...r,wenckebach:{...r.wenckebach,explanation:e.target.value}}))}/></label>{instructor&&<div className="instructor-answer-key"><strong>Wenckebach/Mobitz I</strong><span>Progressive AH/PR prolongation, dropped conduction, grouped beating, reset.</span></div>}</article>
 <article className="assessment-panel task-two-card task-two-ecg"><h2>Five ECG interpretations — 5 marks</h2>{taskTwoEcgCases.map((c,i)=><div className="task-two-ecg-row" key={c.id}><PatternStrip kind={c.label}/><select value={responses.ecgAnswers[i]} onChange={e=>setResponses(r=>({...r,ecgAnswers:r.ecgAnswers.map((v,j)=>j===i?e.target.value:v)}))}><option value="">Select…</option>{taskTwoEcgOptions.map(o=><option key={o}>{o}</option>)}</select>{instructor&&<small>{c.answer}</small>}</div>)}</article></section>
 <footer className="assessment-footer"><button className="assessment-primary" onClick={submit}>Mark Task 2</button><span>{attempts.length} local attempt{attempts.length===1?'':'s'}</span></footer>
 {result&&result.score<22&&<section className="assessment-panel task-two-feedback"><h2>Feedback</h2>{[...result.snrt.feedback,...result.patternRecognition.feedback,...result.wenckebach.feedback,...result.ecg.feedback].map((f,i)=><p key={`${f}-${i}`}>{f}</p>)}</section>}
 </main>;
}
